import { library } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';

// Tell Font Awesome to skip adding CSS automatically since we imported above
config.autoAddCss = false;

import {
  faShoppingBasket,
  faHome,
  faCar,
  faUtensils,
  faPlane,
  faGamepad,
  faGraduationCap,
  faHeartbeat,
  faShoppingBag,
  faEllipsisH,
  faMoneyBill,
  faBriefcase,
  faDumbbell,
  faWifi,
  faBook,
  faPalette,
  faMusic,
  faBaby,
  faPaw,
  faTools,
  faPlus,
  faCamera,
  faCalendar,
  faTags,
  faReceipt,
  faRepeat,
  faArrowRight,
  faSpinner,
  faRobot,
  faLock,
  faCreditCard,
  faChartLine,
  faSignOutAlt,
  faFingerprint,
  faEye,
  faShieldAlt,
  faKey,
  faLightbulb,
  faExclamationTriangle
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library
library.add(
  faShoppingBasket,
  faHome,
  faCar,
  faUtensils,
  faPlane,
  faGamepad,
  faGraduationCap,
  faHeartbeat,
  faShoppingBag,
  faEllipsisH,
  faMoneyBill,
  faBriefcase,
  faDumbbell,
  faWifi,
  faBook,
  faPalette,
  faMusic,
  faBaby,
  faPaw,
  faTools,
  faPlus,
  faCamera,
  faCalendar,
  faTags,
  faReceipt,
  faRepeat,
  faArrowRight,
  faSpinner,
  faRobot,
  faLock,
  faCreditCard,
  faChartLine,
  faSignOutAlt,
  faFingerprint,
  faEye,
  faShieldAlt,
  faKey,
  faLightbulb,
  faExclamationTriangle
); 